name: lua5.3

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.operating_system}}
    strategy:
      fail-fast: false
      matrix:
        lua_version: ["5.3"]
        operating_system: ["ubuntu-latest", "macos-latest", "windows-latest"]
    name: ${{matrix.operating_system}}-${{matrix.lua_version}}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{matrix.lua_version}}
      - run: |
          lua ./specs.lua
